name: Package Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.9'
            architecture: 'x64'
            cache: 'pip'
      - name: Pip Install
        run: python -m pip install --upgrade pip
      - name: Requirements Install
        run: pip install -r requirements.txt
      - name: Install Pyinstaller
        run: pip install pyinstaller
      - name: Create Executable File
        run: pyinstaller -F "main.py" --clean --dist ./out --name "DGLabMouseListener"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CxKitty For Windows x64
          path: |
            out
